private/teste.txt

➡️  Nessa pasta ficarão os arquivos referentes ao momento em que o usuário faz o login.
➡️ Criei um arquivo `.txt` só para ela aparecer no repositório para todos :octocat: , pois, quando enviamos uma pasta vazia ela não aparece no repositório remoto.

Pasta private

---

classes/denunciations/Denunciation.class.php
classes/inheritances/Social.class.php
classes/inheritances/User.class.php
classes/messages/Message.class.php
classes/schools/Courses.class.php
classes/schools/Module.class.php
classes/schools/School.class.php
classes/schools/Subjects.class.php
classes/schools/Teacher.class.php
classes/solicitations/Solicitation.class.php
classes/users/Company.class.php
classes/users/Student.class.php
database/connection.php
database/script/help.sql
database/script/script.txt

O que foi feito:
- Criação das tabelas do banco;
- Script `.txt` com as tabelas;
- Criação das classes.

Database e classes

---

classes/schools/Module.class.php
private/adm/pages/register/register-module/search-module.page.php
private/adm/pages/register/register-teacher/list-teacher.page.php
private/adm/pages/register/register-teacher/search-teacher.page.php

Paginação feita na listagem de módulos!
http://localhost/project/private/adm/pages/register/register-module/list-module.page.php
Adições:
- Uma página copia que servirá para a paginação personalizada de busca (ela é idêntica a pagina de listagem)
- Algumas linhas da paginação de professores foram alteradas pelos motivos de excesso/repetição de um código que já existia

Paginação na listagem de modulos

---

classes/schools/Subject.class.php
database/script/help.sql
database/script/script.txt
private/adm/pages/js/delete-subject.js
private/adm/pages/register/download/materias.xml
private/adm/pages/register/register-module/form-update-module.page.php
private/adm/pages/register/register-subject/controller/delete-subject.controller.php
private/adm/pages/register/register-subject/controller/subject-batch-resgistration.controller.php
private/adm/pages/register/register-subject/controller/subject-unit-registration.controller.php
private/adm/pages/register/register-subject/controller/update-subject.controller.php
private/adm/pages/register/register-subject/form-batch-registration.subject.controller.php
private/adm/pages/register/register-subject/form-register-subject.page.php
private/adm/pages/register/register-subject/form-update-subject.page.php
private/adm/pages/register/register-subject/list-subject.page.php
private/adm/pages/register/registration panel/registration-panel-page.php

**O que foi feito:**
- Listagem de matérias;
- Cadastro;
- Exclusão;
- Update;
- Barra de pesquisa;
- Cadastro em lote.
##
> Antes de fazer os testes adicione o banco que está dento do repô, uma tabela foi removida.

Página de matérias

---

views/pages/login/css-login/valid-login.css
views/pages/login/login-page.php
views/pages/login/validacao.js

* Validação do email institucional (@etec.sp.gov.br) e a validação do help (@help.com.br).
* Verificação da senha (de no minímo 6 caracteres).
-----
* etec@help.c
* nomequalquer@@etec
* julia@etec.sp.gov (a extensão completa é: @etec.sp.gov.br, mas se puderem testar ela por pedaços, eu agradeço).
* help@etec.s
* bruna@help.b(a extensão completa é: @help.com.br, mas se puderem testar ela por pedaços, eu também agradeço muitooo).
[Link de Acesso](http://localhost/project/views/pages/login/login-page.php)

Fix login page

---

private/adm/pages/register/registration panel/registration-panel-page.php

* Foi ajustado a ordem no painel de adicionar informações.
http://localhost/project/private/adm/pages/register/registration%20panel/registration-panel-page.php
* Professores
* Módulos
* Matérias
* Etecs
* Cursos

Fix painel info

---

classes/schools/School.class.php
private/adm/pages/js/pagination-teacher-modal.js
private/adm/pages/register/register-school/controller/pagination-teacher-modal.php
private/adm/pages/register/register-school/list-school.page.php

- Atualizar o banco de dados com o script fornecido dentro do repositório.
- Cadastrar professores
##
- Se a quantidade de professores por pagina é 8
- Se ele mostra os cadastros sem repetição
##

Paginação no modal do professor

---

classes/schools/Course.class.php
private/adm/pages/register/register-course/list-course.page.php

>Detalhes para correção
1. veja se a listagem está condizente com o limite de 6
2. Se a listagem de busca também está condizente.
3. Confira o link para as paginas se está mostrando a paginação certa
##
[Link de acesso](http://localhost/project/private/adm/pages/register/register-course/list-course.page.php)
##

Paginação na página de cursos

---

private/adm/pages/register/register-course/list-course.page.php
private/adm/pages/register/register-subject/list-subject.page.php
private/style/button-delete-course.style.css

* Etec;
http://localhost/project/private/adm/pages/register/register-school/list-school.page.php
* Curso;
http://localhost/project/private/adm/pages/register/register-course/list-course.page.php
* Matéria.
http://localhost/project/private/adm/pages/register/register-subject/list-subject.page.php
* Se as partes da paginação estão centralizadas e com bordas

Ajuste na posiçaõ da paginação

---

classes/schools/Course.class.php
private/adm/pages/js/pagination-modal-course-schools.js
private/adm/pages/js/pagination-modal-course-subjects.js
private/adm/pages/js/pagination-modal-course-teachers.js
private/adm/pages/register/register-course/controller/pagination-modal-course-schools.php
private/adm/pages/register/register-course/controller/pagination-modal-course-subjects.php
private/adm/pages/register/register-course/controller/pagination-modal-course-teachers.php
private/adm/pages/register/register-course/list-course.page.php

- professores
- materias
- etecs
- Cadastrar professores
- materias
- etecs
##
- Se a quantidade de professores por pagina é 8
- se o fluxo da paginação está correto
- se caso uma pagina passe do limite de 8 mais paginas! As outras não devem ter mais paginas se tmb n tiverem passado do limite de 8
##

Paginação das listagens do modal do curso

---

private/adm/pages/dashboard/dashboard.page.php
private/adm/pages/register/register-course/list-course.page.php
private/adm/pages/register/register-module/list-module.page.php
private/adm/pages/register/register-school/list-school.page.php
private/adm/pages/register/register-subject/list-subject.page.php
private/adm/pages/register/register-teacher/list-teacher.page.php
private/adm/pages/register/register.styles.css
private/adm/pages/register/registration panel/registration-panel-page.php

* Hover colocado com sucesso no Botão de sair!!!! 
* Foi adicionado o link do Dashboard em algumas telas.
* ***Testem para ver se o hover no botão sair estão em todas as telas!!!***
* ***Entre em todas as telas e verifiquem se o link para o Dashboard está funcionando.***
http://localhost/project/private/adm/pages/register/registration%20panel/registration-panel-page.php

Fix/Hover no Botão de sair

---

classes/schools/School.class.php
classes/schools/Teacher.class.php
private/school/school-profile.page.php

Agora as Etecs também tem um perfil para ser acessado.
- Como esssa página será acessada através da pesquisa, por enquanto batam nessa `URL` e coloquem no final o `id`de uma Etec já existente no seu banco
```
http://localhost/project/private/school/school-profile.page.php?schoolID=171
``` 
- Não precisará colocar um novo banco.
- Como é só um perfil simples da etec, não temos uma listagem de alunos e nem a visualização da foto de perfil ao clicar.
##

Perfil das Escolas

---

private/student/pages/question/question.page.php
views/pages/register/register-student/register-student.style.css

http://localhost/project/private/student/pages/question/question.page.php
- Text area sem fonte para melhor visualização de personalização
- Toolbar com outra cor, que comporta o hover default do editor
- Seta de voltar no header da pergunta

Fix: colocar seta de voltar na pergunta

---

classes/feed/Following.class.php
classes/researches/Search.class.php
private/student/pages/feed-following/feed-following.page.php
private/student/pages/home/home.page.php

Agora o usuário pode ver o feed somente com o conteúdo das pessoas que ele segue.
- Não é preciso trocar de banco.
- Foi adicionado somente o link na home, deixarei para atualizar as outras páginas de uma só vez com ranking, preferências, etec...

Feed de seguidores

---

views/pages/register/register-student/step2-register-student.page.php

Como a página de solicitção de informações não irá sair, fiz um modal simples para substituir.
> Essa opção será removida da página do administrador.

Solicitação de informação

---

classes/answers/Answer.class.php
classes/denunciations/Denunciation.class.php
classes/questions/Question.class.php
classes/users/StudentMethods.class.php
database/script/help.sql
database/script/script.txt
private/adm/pages/dashboard/dashboard.page.php
private/adm/pages/denunciation/controller/analysis-denunciation.controller.php
private/adm/pages/denunciation/controller/getContexts.controller.php
private/adm/pages/denunciation/controller/resolve-denunciation.controller.php
private/adm/pages/denunciation/detail-profile-student/detail-profile-student.page.php
private/adm/pages/denunciation/detail-question/detail-question.page.php
private/adm/pages/denunciation/list-denunciation.page.php
private/adm/pages/message/list-message.page.php
private/adm/pages/register/register-course/list-course.page.php
private/adm/pages/register/register-module/list-module.page.php
private/adm/pages/register/register-school/list-school.page.php
private/adm/pages/register/register-subject/list-subject.page.php
private/adm/pages/register/register-teacher/list-teacher.page.php
private/adm/pages/register/registration panel/registration-panel-page.php
private/student/pages/detail-perfil-student/detail-perfil-student.page.php

- As denuncias feitas no help aparecerão na listagem
- Tem três tipos `pergunta`, `resposta` e `perfil`
- Ao clicar no link deve aparecer as `detalhes da pergunta` ou `detalhes do perfil do aluno`
- O layout tá bem feio
- O adm só tem acesso as questões, respostas e ao perfil. Nada além disso.
##
- Há um novo banco, caso queira poderá atualizar.
- Caso não queria siga os seguintes passos:
1️⃣  apague a tabela `denunciations` <br>
2️⃣ crie essa primeira tabela
```
CREATE TABLE denunciationsHasContexts(
id INT NOT NULL AUTO_INCREMENT
, PRIMARY KEY(id)
, name VARCHAR(100) NOT NULL
, created_at DATETIME NOT NULL
, updated_at DATETIME
)
```
3️⃣  Deverá cadastrar esses valores:
4️⃣  Cadastre novamente a `denunciations`
```
CREATE TABLE denunciations(
id INT NOT NULL AUTO_INCREMENT
, PRIMARY KEY …
```

Página de denúncia

---

classes/users/Student.class.php
classes/users/StudentMethods.class.php
private/adm/pages/register/register-school/list-school.page.php
private/student/pages/detail-perfil-student/controller/update-perfil-student.controller.php
private/student/pages/detail-perfil-student/detail-perfil-student.page.php

Foi ajustado a formatação de senha, antes mesmo que não tivesse digitado a senha ele pedia. E também foi ajustado o formato da data no `sobre` do perfil do usuário.
##

Ajuste de atualização de senha e formatação de hora

---

classes/users/Student.class.php

A pasta que teremos local e a que estará no repositório, terá a confirmação de email localmente. Para que se não tiver internet no dia da apresentação, dê tudo certo.
- <a href="https://mailtrap.io/">Acesse</a>
- Entre com a conta de email da Cold Wolf, caso não saiba qual é o email e senha. Ele está no trello, no card `GitHub para o grupo`, localizado em `Materiais importantes`.
- Ao acessar, vá ao help e crie uma conta de aluno. Como é local, não precisa ser um email existente.
- Após criar a conta do aluno, volte ao `Mailtrap` e verifique a sua caixa de entrada.
##

Confirmação de email localmente

---

classes/users/StudentController.class.php
private/adm/pages/dashboard/dashboard.page.php
private/adm/pages/list-profiles/controller/block-student.controller.php
private/adm/pages/list-profiles/controller/unlock-student.controller.php
private/adm/pages/list-profiles/list-profiles.page.php

Agora no admistrador temos acesso aos usuários (alunos) e através dessa tela, podemos bloquear e desbloquear o aluno.
##
- Pesquisa de alunos
- Bloquear e desbloquear
- Se o aluno estiver bloqueado não poderá acessar a sua conta
- Se o aluno estiver bloqueado não aparecerá em pesquisas dentro do help, ou no ranking
##

Listagem de usuários no admistrador

---

index.php
private/adm/pages/dashboard/dashboard.page.php
private/adm/pages/dashboard/style.dashboard.css
private/adm/pages/register/register-course/list-course.page.php
private/adm/pages/register/register-school/list-school.page.php
private/adm/pages/register/register.styles.css
private/style/modal-about.style.css
views/landing-page/landing-page-styles.css
views/pages/register/register-profile/register-profile.pages.php
views/pages/register/register-student/step3-register-student.page.php

- O link do modal Fale Conosto agora também pode ser acessado pela NavBar
- A parte de Empresas Parceiras foi alterada para ser uma futura atualização
- O card de seleção de Login da empresa parceira foi alterado para um card disabled
- A label de cadastro no Step3 teve seu texto corrigido
- A posição dos card do Dashboard foi alterada, tendo os contadores acima e o balão abaixo
- A cor das tabs nos modais de Curso e ETECs foi ajustada
- A listagem de cursos no dashboard agora tem seu texto truncado

Reparos da Landing Page

---

.vscode/extensions.json
classes/denunciations/Denunciation.class.php
private/adm/images/components/icon-denunciation.svg
private/adm/pages/dashboard/dashboard.page.php
private/adm/pages/denunciation/detail-profile-student/detail-profile-student.page.php
private/adm/pages/denunciation/detail-question/detail-question.page.php
private/adm/pages/denunciation/list-denunciation.page.php
private/adm/pages/register/register-course/list-course.page.php
private/adm/pages/register/register-module/list-module.page.php
private/adm/pages/register/register-school/list-school.page.php
private/adm/pages/register/register-subject/list-subject.page.php
private/adm/pages/register/register-teacher/list-teacher.page.php
private/adm/pages/register/registration panel/registration-panel-page.php
private/student/styles/list-denunciation.styles.css
private/style/list-denunciation.styles.css
views/styles/button.style.css
views/styles/colors.style.css
views/styles/font-format.style.css

http://localhost/project/private/adm/pages/denunciation/list-denunciation.page.php

Style denunciations

---

private/adm/pages/denunciation/detail-question/detail-question.page.php
private/student/pages/detail-perfil-student/update-perfil-student.page.php
private/student/pages/detail-question/detail-question.page.php
private/student/pages/feed-following/feed-following.page.php
private/student/pages/home/home.page.php
private/student/pages/preferences/preference.page.php

http://localhost/project/private/student/pages/home/home.page.php

Ajustes HEELP

---

classes/questions/Question.class.php

Antes tinham publicações que estavam duplicadas, esse erro foi sanado.
##

Ajuste feed filtrado
